# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2022-09-28T10:07:58+00:00
from typing import List

from pydantic import BaseModel


class Province(BaseModel):
    id: int
    name: str


class Country(BaseModel):
    id: int
    name: str


class GeoObject(BaseModel):
    province: Province
    country: Country


class Hour(BaseModel):
    hour: int
    temp: int
    condition: str


class Forecast(BaseModel):
    date: str
    hours: List[Hour]


class YWResponse(BaseModel):
    now: int
    now_dt: str
    geo_object: GeoObject
    forecasts: List[Forecast]


class CityWeatherData(BaseModel):
    city: str
    date: str
    average_temperature: float
    without_conditions_hours: int
