# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2022-09-28T10:07:58+00:00
import datetime
from typing import List

from pydantic import BaseModel


class Province(BaseModel):
    id: int
    name: str


class Country(BaseModel):
    id: int
    name: str


class GeoObject(BaseModel):
    province: Province
    country: Country


class Hour(BaseModel):
    hour: int
    hour_ts: int
    temp: int
    feels_like: int
    icon: str
    condition: str
    cloudness: float
    prec_type: int
    prec_strength: float
    is_thunder: bool
    wind_dir: str
    wind_speed: float
    wind_gust: float
    pressure_mm: int
    pressure_pa: int
    humidity: int
    uv_index: int
    prec_mm: float
    prec_period: int
    prec_prob: int


class Forecast(BaseModel):
    date: str
    hours: List[Hour]


class YWResponse(BaseModel):
    now: int
    now_dt: str
    geo_object: GeoObject
    forecasts: List[Forecast]


class CityWeatherData(BaseModel):
    city: str  # TODO Enum
    date: datetime.date
    average_temperature: float
    without_conditions_hours: int
